def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appearance_guest', type_='foreignkey')
        batch_op.drop_constraint('fk_appearance_episode', type_='foreignkey')
        batch_op.create_foreign_key('fk_appearance_guest', 'guest', ['guest_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_appearance_episode', 'episode', ['episode_id'], ['id'], ondelete='CASCADE')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appearance_guest', type_='foreignkey')
        batch_op.drop_constraint('fk_appearance_episode', type_='foreignkey')
        batch_op.create_foreign_key('fk_appearance_guest', 'guest', ['guest_id'], ['id'])
        batch_op.create_foreign_key('fk_appearance_episode', 'episode', ['episode_id'], ['id'])
