"""empty message

Revision ID: 1f73a2301ca0
Revises: 4b9def4cbaed
Create Date: 2025-04-06 14:33:42.979337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f73a2301ca0'
down_revision = '4b9def4cbaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'guest', ['guest_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'episode', ['episode_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'episode', ['episode_id'], ['id'])
        batch_op.create_foreign_key(None, 'guest', ['guest_id'], ['id'])

    # ### end Alembic commands ###
