"""Initial migration

Revision ID: 4b9def4cbaed
Revises: 24c04e9fad27
Create Date: 2025-04-06 14:24:34.765753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9def4cbaed'
down_revision = '24c04e9fad27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('description')

    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
